name: darkit
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cupy
  - ninja
  - pytorch
  - pygraphviz
  - torchvision
  - python=3.9
  - pytorch-cuda=12.1
  - cuda-nvcc=12.1
  - cuda-toolkit=12.1
  - cuda-compiler=12.1
