name: darkit
channels:
    - nvidia
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    # CUDA
    - cudatoolkit=11.8
    - cuda-nvcc=11.8
    - cuda-compiler=11.8
    # 科学计算库
    - cupy
    - pytorch
    - torchvision
    - pytorch-cuda=11.8
    # 开发工具
    - ninja
    - pygraphviz
